import { createContext, useContext, useState, type ReactNode } from 'react';

export type Language = 'en' | 'zh' | 'ru' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.hospitals': 'Hospitals',
    'nav.packages': 'Packages',
    'nav.process': 'Process',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'hero.title': 'World-Class Healthcare in China',
    'hero.subtitle': 'From airport pickup to treatment completion — seamless medical travel with transparent pricing, multilingual support, and access to top-tier Chinese hospitals.',
    'hero.cta.primary': 'Explore Packages',
    'hero.cta.secondary': 'View Hospitals',
    'stats.patients': 'Patients Served',
    'stats.hospitals': 'Partner Hospitals',
    'stats.countries': 'Countries Covered',
    'stats.satisfaction': 'Satisfaction Rate',
    'features.title': 'Why Choose MediChina',
    'features.subtitle': 'We handle everything so you can focus on your health',
    'features.transparent.title': 'Transparent Pricing',
    'features.transparent.desc': 'Know your costs upfront. No hidden fees. Real-time cost comparison with US, Europe, and Singapore.',
    'features.language.title': 'Multilingual Support',
    'features.language.desc': 'Professional medical interpreters in English, Russian, Arabic, Indonesian and more. 24/7 support.',
    'features.efficiency.title': 'Unmatched Efficiency',
    'features.efficiency.desc': 'From diagnosis to surgery in days, not months. Same-day CT scans and expert consultations.',
    'features.tcm.title': 'Traditional Chinese Medicine',
    'features.tcm.desc': 'Experience acupuncture, herbal therapy, and wellness treatments alongside modern medicine.',
    'packages.title': 'Popular Health Packages',
    'packages.subtitle': 'Start your journey with our affordable, all-inclusive packages',
    'packages.from': 'From',
    'packages.book': 'Book Now',
    'packages.detail': 'View Details',
    'testimonials.title': 'Patient Stories',
    'testimonials.subtitle': 'Real experiences from patients around the world',
    'cta.title': 'Ready to Start Your Healthcare Journey?',
    'cta.subtitle': 'Get a free consultation and personalized treatment plan within 24 hours',
    'cta.button': 'Get Free Consultation',
    'footer.tagline': 'Your gateway to world-class healthcare in China',
    'footer.services': 'Services',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.copyright': 'MediChina. All rights reserved.',
    'hospitals.title': 'Partner Hospitals',
    'hospitals.subtitle': 'Access 470+ accredited hospitals across China\'s top medical cities',
    'hospitals.search': 'Search by city, specialty, or hospital name...',
    'hospitals.filter.all': 'All Cities',
    'hospitals.filter.shanghai': 'Shanghai',
    'hospitals.filter.beijing': 'Beijing',
    'hospitals.filter.guangzhou': 'Guangzhou',
    'hospitals.filter.shenzhen': 'Shenzhen',
    'hospitals.specialty': 'Specialties',
    'hospitals.book': 'Inquire Now',
    'packages.page.title': 'Health Packages & Experiences',
    'packages.page.subtitle': 'From preventive checkups to Traditional Chinese Medicine wellness journeys',
    'packages.category.checkup': 'Health Checkup',
    'packages.category.specialist': 'Specialist Screening',
    'packages.category.tcm': 'TCM Experience',
    'packages.category.dental': 'Dental Care',
    'packages.includes': 'Package Includes',
    'packages.duration': 'Duration',
    'process.title': 'How It Works',
    'process.subtitle': 'Five simple steps from inquiry to treatment completion',
    'process.step1.title': 'Online Inquiry',
    'process.step1.desc': 'Submit your medical history and requirements. Get a free preliminary assessment within 24 hours.',
    'process.step2.title': 'Treatment Plan',
    'process.step2.desc': 'Receive a detailed plan with hospital options, doctor profiles, transparent pricing, and travel guidance.',
    'process.step3.title': 'Arrival & Transfer',
    'process.step3.desc': 'Airport pickup, hotel check-in, and dedicated patient coordinator. Visa-free entry for 77 countries.',
    'process.step4.title': 'Treatment',
    'process.step4.desc': 'Personal medical interpreter accompanies you throughout. World-class facilities and expert care.',
    'process.step5.title': 'Follow-up Care',
    'process.step5.desc': 'Post-treatment follow-up via video call. Medical report translation. Continued support after return.',
    'about.title': 'About MediChina',
    'about.subtitle': 'Bridging global patients with China\'s exceptional healthcare system',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To make world-class Chinese healthcare accessible to patients worldwide by eliminating language barriers, simplifying complex processes, and providing end-to-end support that ensures a seamless medical travel experience.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To become the world\'s most trusted platform for medical travel to China, connecting millions of international patients with the best hospitals, doctors, and treatment options across the country.',
    'about.team.title': 'Our Team',
    'about.team.desc': 'Founded by healthcare professionals and international business experts, our team combines deep medical knowledge with cross-cultural expertise to deliver exceptional patient experiences.',
    'about.values.title': 'Our Core Values',
    'about.values.transparency': 'Transparency',
    'about.values.transparency.desc': 'Clear pricing, honest communication, no hidden costs',
    'about.values.compassion': 'Compassion',
    'about.values.compassion.desc': 'Treating every patient like family',
    'about.values.excellence': 'Excellence',
    'about.values.excellence.desc': 'Only partnering with top-tier accredited hospitals',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We are here to help you 24/7',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.whatsapp': 'WhatsApp',
    'contact.address': 'Shanghai, China',
  },
  zh: {
    'nav.home': '首页',
    'nav.hospitals': '医院',
    'nav.packages': '套餐',
    'nav.process': '流程',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'hero.title': '中国顶级医疗服务',
    'hero.subtitle': '从机场接机到治疗完成 — 透明定价、多语言支持、直通中国顶级三甲医院的一站式医疗旅行服务。',
    'hero.cta.primary': '探索套餐',
    'hero.cta.secondary': '查看医院',
    'stats.patients': '服务患者',
    'stats.hospitals': '合作医院',
    'stats.countries': '覆盖国家',
    'stats.satisfaction': '满意度',
    'features.title': '为什么选择 MediChina',
    'features.subtitle': '我们处理一切，让您专注于健康',
    'features.transparent.title': '透明定价',
    'features.transparent.desc': '提前知道所有费用。无隐藏收费。与美国、欧洲和新加坡的实时成本对比。',
    'features.language.title': '多语言支持',
    'features.language.desc': '专业医疗翻译团队，支持英语、俄语、阿拉伯语、印尼语等。7x24小时服务。',
    'features.efficiency.title': '极致效率',
    'features.efficiency.desc': '从诊断到手术只需数天，而非数月。当天CT检查和专家会诊。',
    'features.tcm.title': '传统中医',
    'features.tcm.desc': '体验针灸、草药疗法和健康养生，与现代医学完美结合。',
    'packages.title': '热门健康套餐',
    'packages.subtitle': '从我们高性价比的全包套餐开始您的健康之旅',
    'packages.from': '起价',
    'packages.book': '立即预订',
    'packages.detail': '查看详情',
    'testimonials.title': '患者故事',
    'testimonials.subtitle': '来自世界各地患者的真实体验',
    'cta.title': '准备好开始您的医疗之旅了吗？',
    'cta.subtitle': '24小时内获得免费咨询和个性化治疗方案',
    'cta.button': '获取免费咨询',
    'footer.tagline': '通往中国顶级医疗的门户',
    'footer.services': '服务',
    'footer.company': '公司',
    'footer.support': '支持',
    'footer.copyright': 'MediChina. 保留所有权利。',
    'hospitals.title': '合作医院',
    'hospitals.subtitle': '覆盖中国顶级医疗城市的470+认证医院',
    'hospitals.search': '按城市、专科或医院名称搜索...',
    'hospitals.filter.all': '全部城市',
    'hospitals.filter.shanghai': '上海',
    'hospitals.filter.beijing': '北京',
    'hospitals.filter.guangzhou': '广州',
    'hospitals.filter.shenzhen': '深圳',
    'hospitals.specialty': '专科',
    'hospitals.book': '立即咨询',
    'packages.page.title': '健康套餐与体验',
    'packages.page.subtitle': '从预防性体检到传统中医养生之旅',
    'packages.category.checkup': '健康体检',
    'packages.category.specialist': '专科筛查',
    'packages.category.tcm': '中医体验',
    'packages.category.dental': '牙科护理',
    'packages.includes': '套餐包含',
    'packages.duration': '时长',
    'process.title': '服务流程',
    'process.subtitle': '从咨询到治疗完成的五个简单步骤',
    'process.step1.title': '在线咨询',
    'process.step1.desc': '提交您的病史和需求。24小时内获得免费初步评估。',
    'process.step2.title': '治疗方案',
    'process.step2.desc': '接收详细方案，包括医院选择、医生介绍、透明定价和旅行指导。',
    'process.step3.title': '抵达接送',
    'process.step3.desc': '机场接机、酒店入住、专属患者协调员。77国免签入境。',
    'process.step4.title': '治疗',
    'process.step4.desc': '专业医疗翻译全程陪同。世界级设施和专家护理。',
    'process.step5.title': '随访护理',
    'process.step5.desc': '通过视频通话进行术后随访。医疗报告翻译。回国后持续支持。',
    'about.title': '关于 MediChina',
    'about.subtitle': '连接全球患者与中国卓越的医疗体系',
    'about.mission.title': '我们的使命',
    'about.mission.desc': '通过消除语言障碍、简化复杂流程、提供端到端支持，让全球患者都能享受到中国世界级的医疗服务。',
    'about.vision.title': '我们的愿景',
    'about.vision.desc': '成为全球最受信赖的中国医疗旅行平台，连接数百万国际患者与国内最优质的医院、医生和治疗方案。',
    'about.team.title': '我们的团队',
    'about.team.desc': '由医疗专业人士和国际商务专家创立，我们的团队将深厚的医疗知识与跨文化专业能力相结合，提供卓越的患者体验。',
    'about.values.title': '核心价值观',
    'about.values.transparency': '透明',
    'about.values.transparency.desc': '清晰定价、真诚沟通、无隐藏费用',
    'about.values.compassion': '关爱',
    'about.values.compassion.desc': '像家人一样对待每一位患者',
    'about.values.excellence': '卓越',
    'about.values.excellence.desc': '只与顶级认证医院合作',
    'contact.title': '联系我们',
    'contact.subtitle': '我们7x24小时为您服务',
    'contact.email': '邮箱',
    'contact.phone': '电话',
    'contact.whatsapp': 'WhatsApp',
    'contact.address': '中国上海',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.hospitals': 'Больницы',
    'nav.packages': 'Пакеты',
    'nav.process': 'Процесс',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'hero.title': 'Мировое Здравоохранение в Китае',
    'hero.subtitle': 'От встречи в аэропорту до завершения лечения — бесшовный медицинский туризм с прозрачным ценообразованием и многоязычной поддержкой.',
    'hero.cta.primary': 'Смотреть Пакеты',
    'hero.cta.secondary': 'Смотреть Больницы',
    'stats.patients': 'Пациентов',
    'stats.hospitals': 'Партнерских Больниц',
    'stats.countries': 'Стран',
    'stats.satisfaction': 'Удовлетворенность',
    'features.title': 'Почему MediChina',
    'features.subtitle': 'Мы берем на себя все заботы, чтобы вы могли сосредоточиться на здоровье',
    'features.transparent.title': 'Прозрачное Ценообразование',
    'features.transparent.desc': 'Знайте стоимость заранее. Никаких скрытых платежей. Сравнение цен с США и Европой.',
    'features.language.title': 'Многоязычная Поддержка',
    'features.language.desc': 'Профессиональные медицинские переводчики. Поддержка 24/7 на русском и других языках.',
    'features.efficiency.title': 'Высокая Эффективность',
    'features.efficiency.desc': 'От диагностики до операции за дни, а не месяцы. КТ в день обращения.',
    'features.tcm.title': 'Традиционная Китайская Медицина',
    'features.tcm.desc': 'Иглоукалывание, фитотерапия и оздоровительные процедуры наряду с современной медициной.',
    'packages.title': 'Популярные Пакеты',
    'packages.subtitle': 'Начните путешествие с наших доступных комплексных пакетов',
    'packages.from': 'От',
    'packages.book': 'Забронировать',
    'packages.detail': 'Подробнее',
    'testimonials.title': 'Истории Пациентов',
    'testimonials.subtitle': 'Реальные отзывы пациентов со всего мира',
    'cta.title': 'Готовы Начать Свое Медицинское Путешествие?',
    'cta.subtitle': 'Получите бесплатную консультацию и индивидуальный план лечения в течение 24 часов',
    'cta.button': 'Бесплатная Консультация',
    'footer.tagline': 'Ваш путь к мировому здравоохранению в Китае',
    'footer.services': 'Услуги',
    'footer.company': 'Компания',
    'footer.support': 'Поддержка',
    'footer.copyright': 'MediChina. Все права защищены.',
    'hospitals.title': 'Партнерские Больницы',
    'hospitals.subtitle': 'Доступ к 470+ аккредитованным больницам в лучших медицинских городах Китая',
    'hospitals.search': 'Поиск по городу, специальности или названию...',
    'hospitals.filter.all': 'Все Города',
    'hospitals.filter.shanghai': 'Шанхай',
    'hospitals.filter.beijing': 'Пекин',
    'hospitals.filter.guangzhou': 'Гуанчжоу',
    'hospitals.filter.shenzhen': 'Шэньчжэнь',
    'hospitals.specialty': 'Специальности',
    'hospitals.book': 'Узнать',
    'packages.page.title': 'Пакеты и Программы',
    'packages.page.subtitle': 'От профилактических обследований до программ ТКМ',
    'packages.category.checkup': 'Медосмотр',
    'packages.category.specialist': 'Специализированное Обследование',
    'packages.category.tcm': 'Опыт ТКМ',
    'packages.category.dental': 'Стоматология',
    'packages.includes': 'Включено',
    'packages.duration': 'Длительность',
    'process.title': 'Как Это Работает',
    'process.subtitle': 'Пять простых шагов от заявки до завершения лечения',
    'process.step1.title': 'Онлайн-Заявка',
    'process.step1.desc': 'Отправьте историю болезни. Бесплатная оценка в течение 24 часов.',
    'process.step2.title': 'План Лечения',
    'process.step2.desc': 'Детальный план с выбором больницы, профилями врачей и прозрачными ценами.',
    'process.step3.title': 'Прибытие и Трансфер',
    'process.step3.desc': 'Встреча в аэропорту, заселение, координатор. Безвизовый въезд для 77 стран.',
    'process.step4.title': 'Лечение',
    'process.step4.desc': 'Персональный переводчик сопровождает вас. Мировой уровень медицины.',
    'process.step5.title': 'Последующее Наблюдение',
    'process.step5.desc': 'Видео-консультации после лечения. Перевод отчетов. Поддержка после возвращения.',
    'about.title': 'О MediChina',
    'about.subtitle': 'Связываем пациентов со всего мира с исключительной системой здравоохранения Китая',
    'about.mission.title': 'Наша Миссия',
    'about.mission.desc': 'Сделать мировое китайское здравоохранение доступным для пациентов по всему миру, устраняя языковые барьеры и упрощая сложные процессы.',
    'about.vision.title': 'Наше Видение',
    'about.vision.desc': 'Стать самой надежной платформой медицинского туризма в Китай, соединяя миллионы пациентов с лучшими больницами и врачами.',
    'about.team.title': 'Наша Команда',
    'about.team.desc': 'Основана профессионалами здравоохранения и экспертами международного бизнеса, наша команда сочетает глубокие медицинские знания с межкультурной экспертизой.',
    'about.values.title': 'Наши Ценности',
    'about.values.transparency': 'Прозрачность',
    'about.values.transparency.desc': 'Честные цены, ясная коммуникация, никаких скрытых расходов',
    'about.values.compassion': 'Сострадание',
    'about.values.compassion.desc': 'Относимся к каждому пациенту как к семье',
    'about.values.excellence': 'Превосходство',
    'about.values.excellence.desc': 'Сотрудничаем только с лучшими аккредитованными больницами',
    'contact.title': 'Контакты',
    'contact.subtitle': 'Мы на связи 24/7',
    'contact.email': 'Email',
    'contact.phone': 'Телефон',
    'contact.whatsapp': 'WhatsApp',
    'contact.address': 'Шанхай, Китай',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.hospitals': 'المستشفيات',
    'nav.packages': 'الباقات',
    'nav.process': 'العملية',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    'hero.title': 'رعاية صحية عالمية المستوى في الصين',
    'hero.subtitle': 'من استقبال المطار إلى إكمال العلاج — سفر طبي سلس بتسعير شفاف ودعم متعدد اللغات ووصول إلى أفضل المستشفيات الصينية.',
    'hero.cta.primary': 'استكشف الباقات',
    'hero.cta.secondary': 'عرض المستشفيات',
    'stats.patients': 'المرضى المخدومين',
    'stats.hospitals': 'المستشفيات الشريكة',
    'stats.countries': 'الدول المشمولة',
    'stats.satisfaction': 'معدل الرضا',
    'features.title': 'لماذا تختار MediChina',
    'features.subtitle': 'نحن نتولى كل شيء حتى تتمكن من التركيز على صحتك',
    'features.transparent.title': 'تسعير شفاف',
    'features.transparent.desc': 'اعرف تكاليفك مقدماً. بدون رسوم خفية. مقارنة تكلفة فورية مع أمريكا وأوروبا وسنغافورة.',
    'features.language.title': 'دعم متعدد اللغات',
    'features.language.desc': 'مترجمون طبيون محترفون بالإنجليزية والروسية والعربية والإندونيسية والمزيد. دعم 24/7.',
    'features.efficiency.title': 'كفاءة لا مثيل لها',
    'features.efficiency.desc': 'من التشخيص إلى الجراحة في أيام وليس أشهراً. أشعة CT واستشارات خبراء في نفس اليوم.',
    'features.tcm.title': 'الطب الصيني التقليدي',
    'features.tcm.desc': 'جرب الوخز بالإبر والعلاج بالأعشاب والعلاجات الصحية إلى جانب الطب الحديث.',
    'packages.title': 'باقات الصحة الشائعة',
    'packages.subtitle': 'ابدأ رحلتك مع باقاتنا الشاملة بأسعار معقولة',
    'packages.from': 'من',
    'packages.book': 'احجز الآن',
    'packages.detail': 'عرض التفاصيل',
    'testimonials.title': 'قصص المرضى',
    'testimonials.subtitle': 'تجارب حقيقية من مرضى من جميع أنحاء العالم',
    'cta.title': 'هل أنت مستعد لبدء رحلتك العلاجية؟',
    'cta.subtitle': 'احصل على استشارة مجانية وخطة علاج مخصصة في غضون 24 ساعة',
    'cta.button': 'احصل على استشارة مجانية',
    'footer.tagline': 'بوابتك للرعاية الصحية العالمية في الصين',
    'footer.services': 'الخدمات',
    'footer.company': 'الشركة',
    'footer.support': 'الدعم',
    'footer.copyright': 'MediChina. جميع الحقوق محفوظة.',
    'hospitals.title': 'المستشفيات الشريكة',
    'hospitals.subtitle': 'الوصول إلى أكثر من 470 مستشفى معتمد في أفضل المدن الطبية في الصين',
    'hospitals.search': 'البحث حسب المدينة أو التخصص أو اسم المستشفى...',
    'hospitals.filter.all': 'جميع المدن',
    'hospitals.filter.shanghai': 'شنغهاي',
    'hospitals.filter.beijing': 'بكين',
    'hospitals.filter.guangzhou': 'قوانغتشو',
    'hospitals.filter.shenzhen': 'شنتشن',
    'hospitals.specialty': 'التخصصات',
    'hospitals.book': 'استفسر الآن',
    'packages.page.title': 'باقات الصحة والتجارب',
    'packages.page.subtitle': 'من الفحوصات الوقائية إلى رحلات العافية بالطب الصيني التقليدي',
    'packages.category.checkup': 'فحص صحي',
    'packages.category.specialist': 'فحص متخصص',
    'packages.category.tcm': 'تجربة الطب الصيني',
    'packages.category.dental': 'رعاية أسنان',
    'packages.includes': 'يشمل الباقة',
    'packages.duration': 'المدة',
    'process.title': 'كيف يعمل',
    'process.subtitle': 'خمس خطوات بسيطة من الاستفسار إلى إكمال العلاج',
    'process.step1.title': 'استفسار عبر الإنترنت',
    'process.step1.desc': 'أرسل تاريخك الطبي واحتياجاتك. احصل على تقييم أولي مجاني في غضون 24 ساعة.',
    'process.step2.title': 'خطة العلاج',
    'process.step2.desc': 'احصل على خطة مفصلة مع خيارات المستشفى وملفات الأطباء والتسعير الشفاف.',
    'process.step3.title': 'الوصول والنقل',
    'process.step3.desc': 'استقبال المطار وتسجيل الفندق ومنسق مريض مخصص. دخول بدون تأشيرة لـ 77 دولة.',
    'process.step4.title': 'العلاج',
    'process.step4.desc': 'مترجم طبي شخصي يرافقك طوال الوقيت. مرافق عالمية ورعاية خبيرة.',
    'process.step5.title': 'المتابعة',
    'process.step5.desc': 'متابعة ما بعد العلاج عبر مكالمة فيديو. ترجمة التقارير الطبية. دعم مستمر بعد العودة.',
    'about.title': 'عن MediChina',
    'about.subtitle': 'جسر يربط المرضى العالميين بالنظام الصحي الاستثنائي في الصين',
    'about.mission.title': 'مهمتنا',
    'about.mission.desc': 'جعل الرعاية الصحية الصينية عالمية المستوى في متناول المرضى حول العالم من خلال إزالة الحواجز اللغوية وتبسيط العمليات المعقدة وتقديم دعم شامل.',
    'about.vision.title': 'رؤيتنا',
    'about.vision.desc': 'أن نصبح المنصة الأكثر موثوقية في العالم للسفر الطبي إلى الصين، وربط الملايين من المرضى الدوليين بأفضل المستشفيات والأطباء.',
    'about.team.title': 'فريقنا',
    'about.team.desc': 'تأسست من قبل محترفي الرعاية الصحية وخبراء الأعمال الدولية، يجمع فريقنا المعرفة الطبية العميقة بالخبرة الثقافية المتعددة.',
    'about.values.title': 'قيمنا الأساسية',
    'about.values.transparency': 'الشفافية',
    'about.values.transparency.desc': 'تسعير واضح وتواصل صريح بدون تكاليف خفية',
    'about.values.compassion': 'الرحمة',
    'about.values.compassion.desc': 'نعامل كل مريض كأحد أفراد العائلة',
    'about.values.excellence': 'التفوق',
    'about.values.excellence.desc': 'نتعاون فقط مع أفضل المستشفيات المعتمدة',
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'نحن هنا لمساعدتك على مدار الساعة',
    'contact.email': 'البريد الإلكتروني',
    'contact.phone': 'الهاتف',
    'contact.whatsapp': 'واتساب',
    'contact.address': 'شنغهاي، الصين',
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'}>{children}</div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
